parameters:
  - name: environment
    displayName: Environment
    type: string
    default: development
    values:
    - dev
    - acc
    - prod

trigger: none

variables:
  - name: NotebookName
    value: demo_notebook

stages:
    - stage: CI_Build
      displayName: CI
      jobs:
      - job: CI
        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.7'
            inputs:
              versionSpec: 3.7