trigger: none

pool: Azure Pipelines

parameters:
- name: environment
  displayName: Environment
  default: d
  values:
  - d
  - t
  - a
  - p

variables:
- template: ../../conf/${{ parameters.environment }}/variables.yml

stages:
- stage: Stage_ADB
  jobs:
  - job: CreateADB
    displayName: Create  ADB
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Databricks ARM-Template
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        SubscriptionId: $(subscriptionId)
        ResourceGroupName: $(resourceGroupName)
        location: $(location)
        csmFile: '$(System.DefaultWorkingDirectory)/iac/arm/adb/azuredeploy.json'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/iac/arm/adb/azuredeployparam.json'
        #overrideParameters: '-keyVaultName "demo-adb-kv" -bypassNetworkAcls AzureServices -virtualNetworkRules []'
        deploymentMode: 'Incremental'
